version: '3.8'
services:
  prompt: 
    build:
      context: ./promptbox       
    container_name: promptbox
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - GOOGLE_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - mongo
    networks:
      - devops

  mongo:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - devops

volumes:
  mongo_data:
networks:
  devops:
